headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/tmp/insights-cc3po-astro/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Analytics = "true"

[[headers]]
for = "/*_astro/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/*.webp"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.avif"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/fonts/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/blog.html"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*/:index.html"
to = "/blog/:splat"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog.html"
to = "/signal/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/"
to = "/signal/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog"
to = "/signal/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/"
to = "/signal/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]